<a href="https://colab.research.google.com/github/Rahul21j/Vehicle_Image_clf_SVC/blob/main/DS_MINOR_FEB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Link to the images folder:**
https://drive.google.com/drive/folders/1lq7o9NyizT5-w0xtToiX-8SdSD8WKnuu?usp=sharing

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from skimage.io import imread
from skimage.transform import resize
import os
import numpy as np
datadir = '/content/drive/MyDrive/images'

target = []
flat_data = []
categories = ['bikes','cars']

for i in categories:
  path = os.path.join(datadir,i)
  for img in os.listdir(path):
    try:
      img_array=imread(os.path.join(path,img))
      img_resize = resize(img_array,(150,150,3))
      flat_data.append(np.ndarray.flatten(img_resize))
      target.append(i)
    except:
      print(img)

flat_data = np.array(flat_data)
target = np.array(target)

In [ ]:
df = pd.DataFrame(flat_data)
df['Target'] = target
df.head()

          0         1         2         3  ...     67497     67498     67499  Target
0  0.258824  0.474510  0.796078  0.258924  ...  0.054590  0.269461  0.481226   bikes
1  1.000000  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000   bikes
2  0.996078  0.996078  0.996078  0.996078  ...  0.996078  0.996078  0.996078   bikes
3  1.000000  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000   bikes
4  0.412013  0.447307  0.506131  0.413813  ...  0.631124  0.670340  0.717399   bikes

[5 rows x 67501 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Columns: 67501 entries, 0 to Target
dtypes: float64(67500), object(1)
memory usage: 16.5+ MB

In [ ]:
x = df.drop('Target' ,axis=1)
y = df.Target

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
train_x,test_x,train_y,test_y = train_test_split(x,y)
model = SVC()
model.fit(train_x,train_y)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
pred = model.predict(train_x)
pred_y = model.predict(test_x)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(train_y,pred)

array([[11,  1],
       [ 0, 12]])

In [ ]:
accuracy_score(train_y,pred)

0.9583333333333334

In [ ]:
confusion_matrix(test_y,pred_y)

array([[2, 1],
       [3, 2]])

In [ ]:
accuracy_score(test_y,pred_y)

0.5

**Testing a new image.**

In [ ]:
datadir = '/content/drive/MyDrive/images/test/bike.jpg'

target = []
flat_data = []

try:
  img_array=imread(datadir)
  img_resize = resize(img_array,(150,150,3))
  flat_data.append(np.ndarray.flatten(img_resize))
  target.append(i)
  #plt.imshow(img_resize)
  #plt.show()
except:
  print(img)

flat_data = np.array(flat_data)
target = np.array(target)

In [ ]:
df1 = pd.DataFrame(flat_data)
df1['Target'] = target
df1

     0    1    2    3    4    5  ...  67495  67496  67497  67498  67499  Target
0  1.0  1.0  1.0  1.0  1.0  1.0  ...    1.0    1.0    1.0    1.0    1.0    cars

[1 rows x 67501 columns]

In [ ]:
pred_y = model.predict(df1.drop('Target', axis=1))
pred_y

array(['bikes'], dtype=object)